server:
  port: 8081

spring:
  application:
    name: backend-service

  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_db
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: telemetry-backend-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  elasticsearch:
    uris: http://localhost:9200
